### ISSUE TITLE
%tutuvar%, halff5 and halff6

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/The_Calling#5]
There is 1 bug with %tutuvar% for _ar3202.baf and _irspell.baf.

EXTEND_BOTTOM function don't seem to replace %tutuvar% with appropriate value. For example, with BGT we have in AR7202.bcs and SIRSPELL.bcs: 

- PlaySound("%tutuvar%halff5")
- PlaySound("%tutuvar%halff6")
- PlaySound("%tutuvar%halff5")
- HasItem("%tutuvar%misc36",Myself)
- TakeItemReplace("cdbpearl","%tutuvar%misc36",Myself)

In addition, for AR7202.bcs, it should be halff05 and halff06 instead of halff5 and halff6

**Comment by CamDawg** [comment]
Fixed in commit https://github.com/Gibberlings3/The_Calling/commit/5042905864dcf09ac609d7da001e2618d9325584
