### ISSUE TITLE
Unlimited Items from Taerom After Reforging the Bracers

### ISSUE THREAD

**Issue by morpheus562** [Gibberlings3/The_Calling#6]
Every time I initiate dialog with Taerom, he gives me a new necklace/amulet from the reforged remnants of the bracers.

**Comment by morpheus562** [comment]
If I request to destroy the bracers, it goes into an infinite loop where I get 1000exp each time I initiate dialog with Taerom.

**Comment by CamDawg** [comment]
Cheers, fixed in https://github.com/Gibberlings3/The_Calling/commit/af5b9e22cf33e935433073ceb13951c57b7a8cde
